replicaCount: 2

image:
  repository: 518394500999.dkr.ecr.eu-central-1.amazonaws.com/lawyal/flask-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

resources: {}
