name: App Deploy (Helm)

on:
  workflow_dispatch:   # manual trigger (can also be push to main if you prefer)

permissions:
  id-token: write
  contents: read

jobs:
  app:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-central-1
      ECR_REGISTRY: 518394500999.dkr.ecr.eu-central-1.amazonaws.com
      ECR_REPOSITORY: lawyal/flask-app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::518394500999:role/GitHubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name lawyal-eks --region $AWS_REGION

      - name: Get Latest Image by Push Date
        id: latest
        run: |
          LATEST_TAG=$(aws ecr describe-images \
            --repository-name $ECR_REPOSITORY \
            --region $AWS_REGION \
            --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' \
            --output text)

          if [ -z "$LATEST_TAG" ] || [ "$LATEST_TAG" = "None" ]; then
            echo "❌ No images found in ECR!"
            exit 1
          fi

          echo "➡️ Using latest pushed image tag: $LATEST_TAG"
          echo "version_tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Deploy App with Helm
        run: |
          helm upgrade --install flask-app ./helm/flask-app \
            --set image.repository=$ECR_REGISTRY/$ECR_REPOSITORY \
            --set image.tag=${{ steps.latest.outputs.version_tag }}
